name: Tag Version

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Determine version bump
        id: version_bump
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if echo "$commit_message" | grep -q "BREAKING CHANGE\|major:"; then
            echo "bump=major" >> $GITHUB_ENV
          elif echo "$commit_message" | grep -q "feat:\|minor:"; then
            echo "bump=minor" >> $GITHUB_ENV
          else
            echo "bump=patch" >> $GITHUB_ENV
          fi

      - name: Bump version and push tag
        run: |
          latest_tag="$LATEST_TAG"
          version=${latest_tag#v}
          IFS='.' read -r major minor patch <<< "$version"

          case "$bump" in
            major)
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor + 1))
              patch=0
              ;;
            patch)
              patch=$((patch + 1))
              ;;
          esac

          new_tag="v$major.$minor.$patch"
          echo "Creating new tag: $new_tag"

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "$new_tag" -m "Release $new_tag"
          git push origin "$new_tag"
          
          # Update latest tag
          git tag -f latest
          git push -f origin latest